# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1c65bba4d3e4d473debe8dc3d2cb49e3801c259b13fbc43cee4c9f5b83bc6112c972b9e7d50aeb99fdd9355b44daf731af2596c2629dfd95a684168f1a48af0c

test:
  secret_key_base: 751d63d94643a7c2c889889195bdab5f24454b19b11f66964b6c1ee4999766f1589fc8e4556865438df315e3b413c68b78829472717a725146c8012025e190f6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
